steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mbl-livro-amarelo-$BRANCH_NAME:$COMMIT_SHA', '.']
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mbl-livro-amarelo-$BRANCH_NAME:$COMMIT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'mbl-livro-amarelo-$BRANCH_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/mbl-livro-amarelo-$BRANCH_NAME:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--verbosity'
  - 'debug'
images:
- gcr.io/$PROJECT_ID/mbl-livro-amarelo-$BRANCH_NAME